version: '2'
services:
  "nfs-ganesha":
    image: "devopswise/nfs-ganesha:latest"
    container_name: "nfs-ganesha"    
    restart: always
    volumes:
      - "$PWD/data:/export"
    ports:
      - "2049:2049"
      - "111:111/udp"
      - "111:111"
      - "662:662"
      - "38465:38465"
      - "38466:38466"
      - "38467:38467"
    environment:
      GANESHA_OPTIONS: "-N NIV_DEBUG"
